stages:
  - build
  - test
 # - deploy

build-job:
  stage: build
  script:
    - echo "Start building...."
    - docker compose build

test-job:
  stage: test
  script:
    - echo "Start testing...."
    - docker compose up -d
    - sleep 6
    - curl -f http://localhost:5090/random/status || exit 1
  after-script:
    - sudo docker compose down

#deploy-job:      
#  stage: deploy  
#  script:
#    - echo "Deploying application..."
#    - docker compose up -d
