stages:
  - build
  - test
#  - deploy

build-job:
  stage: build
  script:
    - echo "Start building...."
    - docker build -t random-service ./random-service

test-job:
  stage: test
  script:
    - echo "Start testing...."
    - docker run --rm random-service pytest -s -v

#deploy-job:      
#  stage: deploy  
#  script:
#    - echo "Deploying application..."
#    - docker compose up -d
